#!/bin/sh
#=============================
# install packages
#=============================
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install vim
sudo apt-get install apache2
sudo apt-get install php5
sudo apt-get install zip
sudo apt-get install xrdp
#sudo apt-get install git-core
sudo apt-get install arduino
sudo apt-get install python-pip
#=============================
# change password
#=============================
echo "password:name" | chpasswd
#=============================
# set static ip address
#=============================
/etc/network/interfaces
#=============================
# set system time
#=============================
dpkg-reconfigure tzdata
#=============================
# expand memory
#=============================
sudo raspi-config
#=============================
# keyboard settings
#=============================
sudo sed -i 's/EN/SE/g' /etc/default/keyboard
#=============================
# rename device
#=============================
/etc/hostname
sudo sed -i 's/EN/SE/g' /etc/hostname
#=============================
# install pyserial
#=============================
sudo apt-get install python-pip
sudo pip install pyserial
#=============================
# autostart applications
#=============================
/etc/rc.local
#=============================
# vim settings
#=============================
:syntax on
:set number
.vimrc
#=============================
# Arduino loader - ino
#=============================
git clone git://github.com/amperka/ino.git
pip install ino


